version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cloud-postgres
    environment:
      POSTGRES_USER: mrevds
      POSTGRES_PASSWORD: 12121212
      POSTGRES_DB: cloud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: